stages: 
  - build
  - deploy

variables:  
  COMPOSE_HTTP_TIMEOUT: "1200"
  MAJOR_VERSION: 0
  MINOR_VERSION: 1

before_script:  
  - export TAG=$MAJOR_VERSION.$MINOR_VERSION.$CI_PIPELINE_IID
  - echo $TAG
  - export TAG=registry.gitlab.com/sv1r4/shome.assistant:$TAG
  - echo $TAG
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com  

    
build:images:
  image: docker
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  services:
    - docker:dind    
  script:    
    - cd ./src/shome.assistant  
    - docker build -t $TAG .
    - docker push $TAG

    
deploy:laptop-assitant:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - sudo mkdir -p $SECRET_DIR
    - sudo echo $GCP_SERVICE_KEY > $SECRET_DIR/service_key.json
    - if [[ $(docker ps -a -q -f name=$DEPLOY_CONTAINER_NAME) > 0 ]]; then docker rm -f $(docker ps -a -q -f name=$DEPLOY_CONTAINER_NAME) ; else echo docker $DEPLOY_CONTAINER_NAME not runnig ; fi
    - docker run --privileged --restart always -ti -d -e PROJECT_ID=$PROJECT_ID -e SENSIVITY=$SENSIVITY -e "GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/service_key.json" -e MQTT_HOST=$MQTT_HOST -e MQTT_PORT=$MQTT_PORT -v "$SECRET_DIR:/app/secrets/" --name=$DEPLOY_CONTAINER_NAME $TAG  
  only:
    - master
  tags:
    - laptop-assistant
    - shome
